# Generated by Django 3.2.10 on 2022-05-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_google',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.DecimalField(decimal_places=10, max_digits=100)),
                ('order', models.DecimalField(decimal_places=10, max_digits=100)),
                ('priceUSD', models.DecimalField(decimal_places=10, max_digits=100)),
                ('date_arr', models.DateField(db_index=True, max_length=100, unique=True)),
                ('priceRUB', models.DecimalField(decimal_places=10, max_digits=100)),
            ],
        ),
    ]
