# Generated by Django 3.2.10 on 2022-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220522_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_google',
            name='actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='data_google',
            name='date_arr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_google',
            name='num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_google',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_google',
            name='priceRUB',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_google',
            name='priceUSD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
